server:
  port: 9003

spring:
  application:
    name: CustomerOps
  datasource:
    url: jdbc:h2:file:/data/demo1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      show-sql: true
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

